application: apprtc
version: 5 
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images 

- url: /js
  static_dir: js

- url: /.*
  script: apprtc.app
  secure: always
  
inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest
